version: '2'

services:

    redis:
        image: redis
        expose:
            - "6379"
        volumes:
            - ./redis:/data

    nerdzcrush:
        image: nerdzeu/docker-nerdzcrush
        #build: .
        ports:
            - "9999:9999"
        links:
            - redis
        volumes:
            - ./mediacrush:/home/mediacrush
