redis:
    image: redis
    expose:
        - "6379"
    volumes:
        - redis:/data

mediacrush:
    image: nerdzeu/docker-nerdzcrush
    #build: .
    ports:
        - "81:81"
    links:
        - redis
    volumes:
        - mediacrush:/home/mediacrush
